module.exports.descriptors = [
    "Aback", 
    "Abaft", 
    "Abandoned", 
    "Abashed", 
    "Aberrant", 
    "Abhorrent", 
    "Abiding", 
    "Abject", 
    "Ablaze", 
    "Able", 
    "Abnormal", 
    "Aboard", 
    "Aboriginal", 
    "Abortive", 
    "Abounding", 
    "Abrasive",
    "Abrupt", 
    "Absent"
]

module.exports.places = [
    "Abbott", 
    "Abernathy", 
    "Creek-side",
    "Horse-camp", 
    "Ackerly", 
    "Backcountry", 
    "River",
    "Spring", 
    "Agua Dulce", 
    "Bayshore",
    "Alamo Heights", 
    "Alba", "Albany",
    "Alice", 
    "Alice Acres", 
    "Allen", 
    "Alma", 
    "Alpine"
]